### PR TITLE
Better CLI

### PR DESCRIPTION
**Pull request by Unzor**
Updates:
- Add CLI parser

### CODE REVIEW

**Comment by Battledash-2** [comment]
I'll take a look and optimize it a bit.

**Review by Battledash-2 — CHANGES_REQUESTED** [review]
Seems good, although it's a bit lengthy..
Before I merge this, that needs to be addressed:
```js
function cliParser(cmd) {
    let flags = [];
    let commands = [];
    let doNotPush = [];
    let cmdSplit = cmd.split(" ");
    cmdSplit.forEach(function(arg, indexer) {
        if (arg.startsWith("--") || arg.startsWith("-")) {
            flags.push(arg + " " + cmdSplit[indexer + 1]);
            doNotPush.push(cmdSplit[indexer + 1]);
        } else if (!doNotPush.indexOf(str) !== -1) {
            commands.push(arg);
        }
    });
    return {
        commands,
        flags
    };
}
```

**Review by Unzor — COMMENTED** [review]
I don't know what to put here but ok

**Comment by justamirror** [comment]
@Battledash-2 read dm

**Comment by Unzor** [comment]
> Seems good, although it's a bit lengthy.. Before I merge this, that needs to be addressed:
> 
> ```js
> function cliParser(cmd) {
>     let flags = [];
>     let commands = [];
>     let doNotPush = [];
>     let cmdSplit = cmd.split(" ");
>     cmdSplit.forEach(function(arg, indexer) {
>         if (arg.startsWith("--") || arg.startsWith("-")) {
>             flags.push(arg + " " + cmdSplit[indexer + 1]);
>             doNotPush.push(cmdSplit[indexer + 1]);
>         } else if (!doNotPush.indexOf(str) !== -1) {
>             commands.push(arg);
>         }
>     });
>     return {
>         commands,
>         flags
>     };
> }
> ```

Many errors in code, lengthier code works better.

**Comment by Battledash-2** [comment]
This is unoptimized. The CLI is just a placeholder. I'll get to it eventually, without adding 50 lines of code.

**Pull request closed without merging**
